### PR TITLE
Feature/forms

### PR DESCRIPTION
**Pull request by larnedo**
Form elements WIP (widths, heights, paddings... are pending to be substituted by variables)

Please install and review @nguasch @nucliweb @PablitoGS.

### CODE REVIEW

**Comment by PablitoGS** [comment]
@larnedo  I think the classes of state of element should refer to the component or element. For not inheritance in other elements

**Comment by nguasch** [comment]
There are some lint errors (classes names, indentation, ...)

I have some doubts about `.InputGroup--date`: it needs some specific width? now the fields are cut. Also we can see arrows (because is an input[number]) when focusing in Chrome: we need some styles to fix that.

On the markup, there are: `class="alternative"`, is that correct?

@larnedo

**Comment by larnedo** [comment]
@PablitoGS I see the point. I fix it nesting .is-error, .is-success, .is-active and .is-disabled inside .FormGroup class, but I'm not complitly sure that these classes are not going to be used as global classes. We'll solve it when we'll find the case.

**Comment by larnedo** [comment]
@nguasch I'll check `.InputGroup--date` in Chrome and remove `class="alternative"` from Markup.

**Comment by larnedo** [comment]
@nguasch Fixed `type="number"` appereance partialy because we are not applying yet autoprefixer.

Please review @PablitoGS @nguasch.

**Comment by PablitoGS** [comment]
:+1:

**Pull request merged**
