### PR TITLE
Feature/dependencies

### PR DESCRIPTION
**Pull request by nguasch**
I've added sui-components-tabs dependency on package.json

please, review: @PablitoGS @larnedo

### CODE REVIEW

**Comment by PablitoGS** [comment]
:+1:

**Comment by nguasch** [comment]
please, can you review? 
@nucliweb @larnedo

**Comment by larnedo** [comment]
:+1:

**Comment by nguasch** [comment]
Not applicable. I close the pull request and delete the branch. 
NO merged with master

**Pull request closed without merging**
