### PR TITLE
replaced Notification--info by Notification

### PR DESCRIPTION
**Pull request by PablitoGS**
I`ve  replaced the Notification--info for Notification as default class to notifications. Please review @nguasch @larnedo @nucliweb

### CODE REVIEW

**Comment by nucliweb** [comment]
:+1:

**Comment by larnedo** [comment]
@PablitoGS I think `@mixin notification` it's not necessary because it's only needed by the class `.Notification`. The modifiers classes don't need to include the mixin because they just change the background-color, right?

`_notification.scss` must to be renamed to `notification.scss` because the components aren't partials.

**Comment by PablitoGS** [comment]
@larnedo you're right. I´ve deleted mixin and renamed file. Please review

**Comment by nguasch** [comment]
pending to validate and merge this branch: SUI-Framework/SUI#5

**Comment by nguasch** [comment]
:+1:

**Pull request merged**
