### PR TITLE
Tags component

### PR DESCRIPTION
**Pull request by larnedo**
Please review @nucliweb @PablitoGS @nguasch.

Not included:
- Iconfont used as element to close the closable's tag
- Global variables used as borders, positions, ...

### CODE REVIEW

**Comment by nucliweb** [comment]
:+1:

**Comment by nguasch** [comment]
pending to validate and merge this branch: SUI-Framework/SUI#5

**Comment by PablitoGS** [comment]
:+1:

**Comment by PablitoGS** [comment]
reopen PR

**Comment by PablitoGS** [comment]
@larnedo reopen this PR please

**Pull request merged**
