### PR TITLE
Tooltip component

### PR DESCRIPTION
**Pull request by larnedo**
Please review this component @PablitoGS @nguasch @nucliweb. 

I'm not sure if all keyframes must be rename with `tooltip-` prefix or some of them move to a global animations.scss, what do you think?

Not included in this iteration:
- Interaction
- Internal paddings
- Global variables used as borders, positions, ...
- Iconfont used as element to close the tooltip. I've included a `content: 'X';` provisionally to show the action instead of the Iconfont whereas It's not defined.

### CODE REVIEW

**Comment by PablitoGS** [comment]
@larnedo the generic animations like move-up should not be in component?

**Comment by nguasch** [comment]
pending to validate and merge this branch: SUI-Framework/SUI#5

**Comment by nguasch** [comment]
I'm not sure if animations (and keyframes) must be in this .scss or an other different partial (maybe because we'll need global animations).

Otherwise, on Markup there are a style inline, and the title is an /h3 (I'm afraid that a developer just do copy and paste this tag and break the hierarchy)

@larnedo

**Comment by larnedo** [comment]
@nguasch @PablitoGS Yeah, I agree with you about animations.scss. I do that.

@nguasch About the style inline is because it's not JS applied by the moment, so I prefer to keep it since we apply the interaction to see it with the correct format on tablet/desktop resolution. And about the `h3` I see what you mean maybe an `h2` would be better, isn't it? What it happens is that our tooltips has title when the standard doesn't have.

**Comment by larnedo** [comment]
@PablitoGS @nucliweb Please review!

- Removed animations properties from tooltip.scss
- Created a base/animations.scss file

**Comment by nucliweb** [comment]
:+1:

**Comment by PablitoGS** [comment]
:+1:

**Pull request merged**
