### PR TITLE
Stickers component

### PR DESCRIPTION
**Pull request by larnedo**
Included:
- stickers structure
- fonts mixins

Not included:
- stickers with iconfont
- variables to subtitute paddings, positions...

Please review @PablitoGS @nguasch @nucliweb

### CODE REVIEW

**Comment by PablitoGS** [comment]
:+1:

**Comment by nucliweb** [comment]
@larnedo please resolve the conflicts before merge this PR, thanks

**Comment by larnedo** [comment]
@nucliweb Solve it! Thanks :)

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
