### PR TITLE
Feature/headings

### PR DESCRIPTION
**Pull request by nguasch**
added headings partial
(needs update dependencies of sui-base, sui-components-buttons & sui-components-tabs)
If we need to change the appearance of headings, we'll do by classes defined on text-size (under construction)

please, review: @PablitoGS @larnedo

### CODE REVIEW

**Comment by larnedo** [comment]
@nguasch I would fix Markdown to don't include <h6> level because it's not difined by the moment by design. And also I would fix on this way line 23 on _headings.scss to remove <h5> specification.

**Comment by PablitoGS** [comment]
:+1:

**Comment by nguasch** [comment]
@larnedo do you mean change text "Heading level 1" on line 8 (and the next ones) for "XXLarge" (and respectives)?

**Comment by larnedo** [comment]
@nguasch I mean delete line 23 :)

**Comment by nguasch** [comment]
Ok. Done!

**Comment by larnedo** [comment]
:+1:

**Pull request merged**
