### PR TITLE
Feature/fonts

### PR DESCRIPTION
**Pull request by PablitoGS**
I've added fonts partial in base. 
The typography must be imported from base, in the same way that a component. Please review @nguasch @larnedo

### CODE REVIEW

**Comment by larnedo** [comment]
:+1:

**Comment by PablitoGS** [comment]
Please review @nguasch , now this branch is merged with master

**Comment by nguasch** [comment]
@PablitoGS 
We should include rules to simulate text-sizes for headings?

**Comment by PablitoGS** [comment]
@nguasch I've added new rules for text-size

**Comment by nguasch** [comment]
sensacional! :dancer: 
:+1:

**Pull request merged**
