### PR TITLE
added mediaqueries with sizes in utils-size

### PR DESCRIPTION
**Pull request by PablitoGS**
I've added sizes for device, to checkout view the last example in grid. Review please, @nguasch @nucliweb @larnedo

### CODE REVIEW

**Comment by nguasch** [comment]
pending to validate and merge this branch: https://github.com/SUI-Framework/SUI/pull/5

**Comment by nguasch** [comment]
:+1:

**Comment by PablitoGS** [comment]
@nguasch I´ve validated merging new pre commit rules.
review to merge please @larnedo @nucliweb

**Comment by nucliweb** [comment]
:+1:

**Pull request merged**
